### ISSUE TITLE
$roslaunch simpcl mapping.launch

### ISSUE THREAD

**Issue by WangWangPoint** [enesdemirag/point-cloud-filters#1]
$roslaunch simpcl mapping.launch
[mapping.launch] is neither a launch file in package [simpcl] nor is [simpcl] a launch file name
The traceback for the exception was written to the log file.
why?

**Comment by enesdemirag** [comment]
Hi @WangWangPoint !

Sorry, I forgot to mention but you need to source your workspace before that command.
You need to run below command inside your workspace directory.

$ source devel/setup.bash

I'll update README.
